import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import styles from "./page.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <Link className="navlink" href="/">
              Home
            </Link>
            <Link className="navlink" href="/reviews">
              Reviews
            </Link>
          </nav>
        </header>

        <main>
          {children}
        </main>

        <footer>Footer</footer>
      </body>
    </html>
  );
}
